
bonus:
  handler: HelloBonus
  events:
      - event:
          eventType: providers/cloud.firestore/eventTypes/document.write
          resource: projects/speedtest-reports-255907/databases/(default)/documents/referral_records/{uid}
